name: Telegram Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Paketleri Kur
        run: pip install -r requirements.txt

      - name: Botu Çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
